# Generated by Django 5.0.4 on 2024-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(default='622 76 87 10', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'CLIENT',
                'verbose_name_plural': 'CLIENTS',
            },
        ),
    ]
