# Generated by Django 5.0.4 on 2024-04-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CATEGORIE',
                'verbose_name_plural': 'CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Détail', 'Détail'), ('Paquet', 'Paquet'), ('Détail & Entier', 'Détail & Entier')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'MODALITE',
                'verbose_name_plural': 'MODALITES',
            },
        ),
        migrations.CreateModel(
            name='ShapeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'FORME ARTICLE',
                'verbose_name_plural': 'FORME ARTICLES',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimal_storage', models.IntegerField(default=5)),
                ('storage_disponible', models.IntegerField(default=0)),
                ('using', models.CharField(max_length=255, null=True)),
                ('secondary_repercutions', models.CharField(max_length=255, null=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
                ('id_modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.modality')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.shapeitem')),
            ],
            options={
                'verbose_name': 'ARTICLE',
                'verbose_name_plural': 'ARTICLES',
            },
        ),
    ]
