# Generated by Django 5.0.4 on 2024-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=100, unique=True)),
                ('adress', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('product_key', models.CharField(default='GRAPHIKART_FORMATION_2023', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'PHARMACIE',
                'verbose_name_plural': 'PHARMACIES',
            },
        ),
    ]
