# Generated by Django 5.0.4 on 2024-07-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mail_pharmacian', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'PHARMACIEN',
                'verbose_name_plural': 'PHARMACIENS',
            },
        ),
    ]
