# Generated by Django 5.0.4 on 2024-07-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_pharmacian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacian',
        ),
    ]
