# Generated by Django 5.0.4 on 2024-04-15 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('id_medecine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'verbose_name': 'BON',
                'verbose_name_plural': 'BONS',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_command', models.IntegerField()),
                ('item_length', models.IntegerField()),
                ('quantity_stored', models.IntegerField()),
                ('date_livraison', models.DateTimeField(auto_now_add=True)),
                ('code_pharmacian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COMMANDE',
                'verbose_name_plural': 'COMMANDES',
            },
        ),
        migrations.CreateModel(
            name='FactureCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('code_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.command')),
            ],
            options={
                'verbose_name': 'FACTURE COMMANDE',
                'verbose_name_plural': 'FACTURES COMMANDES',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('code_pharmacian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FOURNISSEUR',
                'verbose_name_plural': 'FOURNISSEURS',
            },
        ),
        migrations.CreateModel(
            name='FactureBon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('id_bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.bon')),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.fournisseur')),
            ],
            options={
                'verbose_name': 'BON DE FACTURE',
                'verbose_name_plural': 'BONS DE FACTURE',
            },
        ),
        migrations.CreateModel(
            name='CommandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_stored', models.IntegerField()),
                ('price_buy', models.IntegerField()),
                ('price_sale', models.IntegerField()),
                ('price_sale_per_item', models.IntegerField()),
                ('quantity_in_item', models.IntegerField()),
                ('date_expired', models.DateTimeField(auto_now_add=True)),
                ('code_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.command')),
                ('id_medecine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('id_modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.modality')),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.fournisseur')),
            ],
            options={
                'verbose_name': 'COMMANDE ARTICLE',
                'verbose_name_plural': 'COMMANDES ARTICLES',
            },
        ),
    ]
