# Generated by Django 5.0.4 on 2024-04-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='code_pharmacian',
        ),
    ]
