# Generated by Django 5.0.4 on 2024-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_remove_fournisseur_code_pharmacian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
