# Generated by Django 5.0.4 on 2024-05-07 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prix', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('quantite_en_stock', models.IntegerField(default=0)),
                ('tag', models.ManyToManyField(to='produit.tag')),
            ],
        ),
    ]
