# Generated by Django 5.0.4 on 2024-05-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image du produit'),
        ),
    ]
