# Generated by Django 5.0.4 on 2024-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP'), ('Entreprise', 'Entreprise')], default='Regular', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
