# Generated by Django 5.0.4 on 2024-04-15 16:54

import django.db.models.deletion
import sales.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('commands', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_sale', models.IntegerField()),
                ('quantity_sale', models.IntegerField()),
                ('date_sale', models.DateTimeField(auto_now_add=True)),
                ('code_pharmacian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'VENTE',
                'verbose_name_plural': 'VENTES',
            },
        ),
        migrations.CreateModel(
            name='FactureSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_sale', models.DateTimeField(auto_now_add=True, verbose_name=sales.models.Sale)),
                ('code_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
            options={
                'verbose_name': 'BON DE FACTURE',
                'verbose_name_plural': 'BONS DE FACTURE',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remise', models.IntegerField(null=True)),
                ('quantity_sale', models.IntegerField()),
                ('code_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.command')),
                ('code_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
                ('id_medecine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('id_modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.modality')),
            ],
            options={
                'verbose_name': 'VENTE MEDICAMENT',
                'verbose_name_plural': 'VENTES MEDICAMENTS',
            },
        ),
    ]
