# Generated by Django 5.0.4 on 2024-07-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_client',
        ),
    ]
