# Generated by Django 5.0.4 on 2024-07-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0002_remove_sale_id_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
    ]
